---
abstract: 'Make Moose method modifiers Devel::Cover friendly'
author:
  - 'Chia-liang Kao <clkao@clkao.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-CoverableModifiers
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Devel::Declare: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/clkao/MooseX-CoverableModifiers.git
version: 0.30
